version: 0.0
os: linux
files:
  - source: app/
    destination: /var/www/html/

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/start.sh
      timeout: 60
      runas: root
